config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index, :show, :create] do
    resources :favorites, only: [:create, :destroy]
    resources :terms, only: [:new, :create]
  end

  resources :chat_rooms, only: [:new, :create, :show, :index, :destroy] do
    collection do
      post :help
    end
  end

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  match "/chat_rooms" => "chat_rooms#create", :as => "create_chat", via: [:get, :post]

  mount ActionCable.server => '/cable'

  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chat_room_users, dependent: :destroy
  has_many :users, through: :chat_room_users
  has_many :messages, dependent: :destroy

  default_scope { order('created_at DESC') }
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :terms
  before_action :choose_role

  def index
    @chat_rooms = current_user.chat_rooms
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new

    if @chat_room.users.includes(current_user)
      @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
      @message = Message.new
    else
      flash[:alert] = "Whoops! You don't belong in there!"
      redirect_to chat_rooms_path
    end
  end

  def create
    user = current_user
    chat_rooms = user.chat_rooms
    stepper = User.find_by(username: params[:chat_room][:title])

    chat_rooms.each do |f|
      if f.user_ids.include?(current_user.id) && f.user_ids.include?(stepper.id)
        redirect_to f and return
      end
    end

    @chat_room_new = ChatRoom.new(chat_room_params)
    @chat_room_new.users.push(user, stepper)

    if @chat_room_new.save
      flash[:notice] = "Chat begun!"

      (@chat_room_new.users.uniq - [current_user]).each do |u|
        Notification.create(recipient: u, actor: current_user, action: "started", notifiable: @chat_room_new)
      end

      redirect_to @chat_room_new
    end
  end

  def destroy
    @chat_room = ChatRoom.find(params[:id])

    if @chat_room.destroy
      flash[:notice] = "Chat has been terminated."
      redirect_to chat_rooms_path
    else
      flash[:alert] = "There was an error."
      redirect_to chat_rooms_path
    end
  end

  def help
    @chat_room = ChatRoom.new
    users = User.where.not(id: current_user.id).where(role: "stepper")
    user = users.sample
    @chat_room.users.push(current_user, user)
    @chat_room.title = user.username

    if @chat_room.save
      flash[:notice] = "Chat begun!"

      (@chat_room.users.uniq - [current_user]).each do |u|
        Notification.create(recipient: u, actor: current_user, action: "started", notifiable: @chat_room)
      end

      redirect_to @chat_room
    end
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end
end

app/views/chat_rooms/_chat_room.html.erb
<div class="contains-index">
  <div class="pull-right">
    <%= link_to "End Chat", chat_room, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this chat?'} %>
    <%= link_to "Enter Chat", chat_room_path(chat_room), class: 'btn btn-primary' %>
  </div>
  <% if current_user.id == chat_room.users.first.id %>
    <h4><%= link_to chat_room.users.last.username, user_path(chat_room.users.last) %></h4>
    <small>Started at <%= chat_room.created_at.to_formatted_s(:short) %></small>
  <% elsif current_user.id == chat_room.users.last.id %>
    <h4><%= link_to chat_room.users.first.username, user_path(chat_room.users.first) %></h4>
    <small>Started at <%= chat_room.created_at.to_formatted_s(:short) %></small>
  <% end %>
</div>

app/views/chat_rooms/index.html.erb
<div class="contains-index">
<h1><%= current_user.username %>'s Chats (<%= current_user.chat_rooms.count %>)</h1>
<% if current_user.chat_rooms.count == 0 %>
  <h3>You currently have no active chats!</h3>
<% end %>
</div>
  <%= render @chat_rooms %>

app/views/chat_rooms/new.html.erb
<h1>Add chat room</h1>

<%= form_for @chat_room do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
  </div>

  <%= f.submit "Add!", class: 'btn btn-primary' %>
<% end %>

app/views/chat_rooms/show.html.erb
<div class="contain-chat">
  <% if current_user.username == @chat_room.title %>
    <% (@chat_room.users.uniq - [current_user]).each do |u| %>
      <h1><%= u.username %></h1>
    <% end %>
  <% else %>
    <h1><%= @chat_room.title %></h1>
  <% end %>

  <div class="chat-message-box" id="messages" data-chat-room-id="<%= @chat_room.id %>">
    <%= render @chat_room.messages %>
  </div>

<%= form_for @message, url: '#' do |f| %>
<div class="row">
  <div class="form-group" id="text-box">
    <%= f.text_area :body, class: 'form-control' %>
    <%= f.submit "Send", class: 'btn btn-primary btn-lg', display: "inline" %>
  </div>
</div>
<% end %>
</div>

<script>
$('#text-box').keypress(function(e){
      if(e.which == 13){
           $(this).closest('form').submit();
       }
    });
</script>