config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index, :show, :create] do
    resources :favorites, only: [:create, :destroy]
    resources :terms, only: [:new, :create]
  end

  resources :chat_rooms, only: [:new, :create, :show, :index, :destroy] do
    collection do
      post :help
    end
  end

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  match "/chat_rooms" => "chat_rooms#create", :as => "create_chat", via: [:get, :post]

  mount ActionCable.server => '/cable'

  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'
end

app/models/user.rb
class User < ApplicationRecord
  attr_writer :login
  has_many :chat_room_users, dependent: :destroy
  has_many :chat_rooms, through: :chat_room_users, dependent: :destroy
  has_many :favorites
  has_many :favorited_users, through: :favorites, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :terms
  has_many :notifications, foreign_key: :recipient_id

  validates :bio, length: { maximum: 500 }, presence: true
  validates :catchphrase, length: { in: 5..90 }, presence: true

  enum role: [:seeker, :stepper, :admin]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :lastseenable, :validatable, authentication_keys: [:login]

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_h).first
      end
  end

  def self.search(search)
    where("username LIKE ?", "%#{search}%")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :terms
  before_action :choose_role

  def index
    @users = User.all
    @chat_room = ChatRoom.new

    if params[:search] == "all"
      @users = User.all
    elsif params[:search]
      @users = User.search(params[:search]).order("created_at DESC")
        if @users.count == 0
          [flash[:alert] = "#{params[:search]} was not found"]
          redirect_to users_path
        end
    elsif current_user.stepper?
      @users = User.where.not(id: current_user.id).where('last_seen > ?',10.minutes.ago).where(role: "seeker")
      @favorites = current_user.favorited_users
    elsif current_user.seeker?
      @users = User.where.not(id: current_user.id).where('last_seen > ?',10.minutes.ago).where(role: "stepper")
      @favorites = current_user.favorited_users
    elsif current_user.admin?
      @users = User.all
      @favorites = current_user.favorited_users
    end
  end

  def edit
    @user = current_user
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @user = User.find(params[:id])
    @chat_room = ChatRoom.new
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="container">
  <div class='row'>
    <div class="col">
      <% if mobile_device == 'mobile' || mobile_device == 'tablet' %>
        <div class="contains-search">
          <%= form_tag(users_path, method: 'get', class: 'navbar-form navbar-right') do %>
            <%= search_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search for a user...'  %>
            <%= submit_tag "Search", class: 'btn btn-default', :name => nil %>
          <% end %>
        </div>
      <% end %>
      <% if current_user.favorited_users.any? && @favorites != nil %>
        <h3>Favorites</h3>
            <% @favorites.each do |favorite| %>
              <div class='col-md-4'>
                <div class="profile-card">
                  <%= link_to image_tag("profile.jpg", class: "img-card"), favorite %></h3>
                  <h3><%= link_to favorite.username, favorite %></h3>
                  <h4>Time Sober: <%= favorite.years_sober %> years</h4>
                  <p>Catchphrase: "<%= favorite.catchphrase %>"</p>
                  <% if favorite.last_seen != nil %>
                    <small>Last seen: <%= favorite.last_seen.to_formatted_s(:short) %></small>
                  <% end %>
                  <%= form_for @chat_room, url: create_chat_path(@chat_room) do |f| %>
                    <div class="form-group">
                      <%= f.hidden_field :title,  :value => "#{favorite.username}" %>
                    </div>
                    <%= f.submit "Chat", class: 'btn btn-primary' %>
                  <% end %>
                </div>
            </div>
          <% end %>
        <% end %>
    </div>
  </div>
</div>
<div class="container">
  <div class='row'>
    <div class="col">
      <h3>Users</h3>
      <% if @users.any? %>
      <% @users.each do |user| %>
        <div class='col-md-4'>
          <div class="profile-card">
            <%= link_to image_tag("profile.jpg", class: "img-card"), user %></h3>
            <h3><%= link_to user.username, user %></h3>
            <h4>Time Sober: <%= user.years_sober %> years</h4>
            <p>Catchphrase: "<%= user.catchphrase %>"</p>
            <% if user.last_seen != nil %>
              <small>Last seen: <%= user.last_seen.to_formatted_s(:short) %></small>
            <% end %>
            <%= form_for @chat_room, url: create_chat_path(@chat_room) do |f| %>
              <div class="form-group">
                <%= f.hidden_field :title,  :value => "#{user.username}" %>
              </div>

              <%= f.submit "Chat", class: 'btn btn-primary' %>
            <% end %>
          </div>
        </div>
      <% end %>
      <% else %>
        <div class="contains-none">
          <h3>There are currently no active users! Check back soon!</h3>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="contains-show">
    <%= image_tag 'profile.jpg', class: "img-show" %></br>
    <% if @user == current_user %>
      </br>
      <div>
        <%= link_to "Update Profile", edit_user_registration_path(current_user), class: 'btn btn-primary' %>
      </div>
    <% else %>
      <%= form_for @chat_room, url: create_chat_path(@chat_room) do |f| %>
        <div class="form-group">
          <%= f.hidden_field :title,  :value => "#{@user.username}" %>
        </div>

        <%= f.submit "Chat", class: 'btn btn-primary' %>
      <% end %>
    </br>
      <% if current_user.favorited_users.include?(@user) %>
        <%= link_to user_favorite_path(:user_id => @user.id), class: 'btn btn-danger', method: :delete do %>
          <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; Unfavorite
        <% end %>
      <% else %>
        <%= link_to user_favorites_path(:user_id => @user.id), class: 'btn btn-primary', method: :post do %>
          <i class="glyphicon glyphicon-star"> </i>&nbsp; Favorite
        <% end %>
      <% end %>
    <% end %>
    <h2><%= @user.username %></h2>
    <h3>
      Catchphrase: "<%= @user.catchphrase %>"</br>
    </h3>
    <h4>
      I have <%= @user.years_sober %> years sober
    </h4>
    <% if @user.last_seen != nil && @user != current_user %>
      <small>Last seen: <%= @user.last_seen.to_formatted_s(:short) %></small>
    <% end %>
    <h4>
      My Story:
    </h4>
    <p>
      <%= @user.bio %>
    </p>
  </div>
</div>