config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index, :show, :create] do
    resources :favorites, only: [:create, :destroy]
    resources :terms, only: [:new, :create]
  end

  resources :chat_rooms, only: [:new, :create, :show, :index, :destroy] do
    collection do
      post :help
    end
  end

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  match "/chat_rooms" => "chat_rooms#create", :as => "create_chat", via: [:get, :post]

  mount ActionCable.server => '/cable'

  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_edit.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <h4 class="modal-title" id="myModalLabel">Modal title</h4>
</div>
<div class="modal-body">
  *Modal content comes here*
</div>
<div class="modal-footer">
  <button class="btn btn-primary">Save</button>
</div>

app/views/welcome/edit.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'edit') %>");
$("#modal-window").modal();

app/views/welcome/index.html.erb
<div class="contains">
  <h1 class="display-4">Welcome to 12Step!</h1>
  <p class="lead">Having a rough day? On the verge of a relapse? Sometimes we just need
    someone who we can talk to and, more importantly, relate to. 12Step is an anonymous chat
    app for people in recovery that seeks to fulfill that need. All chats are private, anonymous,
    and self-destruct after 24 hours.
  </p>
  <hr class="my-4">
  <% if current_user %>
  <div align="center"><a data-toggle="modal" href="#myModal" class='btn btn-primary'>What brings you today?</a>
  <%= link_to "HELP!", help_chat_rooms_path, method: :post, class: 'btn btn-primary' %></div>
  <div class="modal" id="myModal">
    <%= render 'shared/status' %>
  </div>
  <% else %>
    <p>
      Click <%= link_to "here", new_user_session_path %> to sign in or
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
    </p>
  <% end %>
</div>