config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index, :show, :create] do
    resources :favorites, only: [:create, :destroy]
    resources :terms, only: [:new, :create]
  end

  resources :chat_rooms, only: [:new, :create, :show, :index, :destroy] do
    collection do
      post :help
    end
  end

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  match "/chat_rooms" => "chat_rooms#create", :as => "create_chat", via: [:get, :post]

  mount ActionCable.server => '/cable'

  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chat_room_users, dependent: :destroy
  has_many :users, through: :chat_room_users
  has_many :messages, dependent: :destroy

  default_scope { order('created_at DESC') }
end

app/models/chat_room_user.rb
class ChatRoomUser < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :favorited_user, class_name: "User"
end

app/models/favorite_user.rb
class FavoriteUser < ApplicationRecord
  belongs_to :favorite
  belongs_to :student
end

app/models/message.rb
class Message < ApplicationRecord
  after_create_commit { MessageBroadcastJob.perform_later(self) }
  
  belongs_to :user
  belongs_to :chat_room

  validates :body, presence: true, length: {minimum: 2, maximum: 1000}

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :actor, class_name: "User"
  belongs_to :notifiable, polymorphic: true

  scope :unread, ->{ where(read_at: nil) }
  scope :recent, ->{ order(created_at: :desc).limit(3) }
end

app/models/stepper.rb
class Stepper < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
end

app/models/term.rb
class Term < ApplicationRecord
  belongs_to :user

  validates :agree, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  attr_writer :login
  has_many :chat_room_users, dependent: :destroy
  has_many :chat_rooms, through: :chat_room_users, dependent: :destroy
  has_many :favorites
  has_many :favorited_users, through: :favorites, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :terms
  has_many :notifications, foreign_key: :recipient_id

  validates :bio, length: { maximum: 500 }, presence: true
  validates :catchphrase, length: { in: 5..90 }, presence: true

  enum role: [:seeker, :stepper, :admin]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :lastseenable, :validatable, authentication_keys: [:login]

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_h).first
      end
  end

  def self.search(search)
    where("username LIKE ?", "%#{search}%")
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  after_create_commit { notify }

  private

  def notify
    Notification.create(event: "New Notification")
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @terms = Term.new
  end

  def create
    @terms = Term.new(terms_params)
    @terms.user = current_user

    if @terms.save
      flash[:notice] = "Thanks & Welcome!"
      redirect_to users_path
    else
      flash[:notice] = "There was an error, please try again"
      render :new
    end
  end

  private

  def terms_params
    params.require(:term).permit(:agree)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :terms
  before_action :choose_role

  def index
    @users = User.all
    @chat_room = ChatRoom.new

    if params[:search] == "all"
      @users = User.all
    elsif params[:search]
      @users = User.search(params[:search]).order("created_at DESC")
        if @users.count == 0
          [flash[:alert] = "#{params[:search]} was not found"]
          redirect_to users_path
        end
    elsif current_user.stepper?
      @users = User.where.not(id: current_user.id).where('last_seen > ?',10.minutes.ago).where(role: "seeker")
      @favorites = current_user.favorited_users
    elsif current_user.seeker?
      @users = User.where.not(id: current_user.id).where('last_seen > ?',10.minutes.ago).where(role: "stepper")
      @favorites = current_user.favorited_users
    elsif current_user.admin?
      @users = User.all
      @favorites = current_user.favorited_users
    end
  end

  def edit
    @user = current_user
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @user = User.find(params[:id])
    @chat_room = ChatRoom.new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.username
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
              opts
  end

  def mobile_device
    agent = request.user_agent
    return "tablet" if agent =~ /(tablet|ipad)|(android(?!.*mobile))/i
    return "mobile" if agent =~ /Mobile/
    return "desktop"
  end    

  def resource_name
   :user
  end

  def resource
   @resource ||= User.new
  end

  def devise_mapping
   @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_counter.html.erb
<li>
  <%= image_tag("icons/notification_bell") %>
  <span  id="notification-counter"><%= counter %></span>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwelveStep</title>
    <%= csrf_meta_tags %>
    <% if Rails.env.production? %>
      <script type="text/javascript">
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-128984800-1', 'auto');
      </script>
    <% end %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-default navbar-static-top" style="background: black;">
      <div class="container">
        <div class="col-md-6">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "12Step", welcome_index_path, class: "navbar-brand" %>
          <div class="navbar-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">
              <% if user_signed_in? %>
                <li><%= link_to "Find Someone", users_path  %></li>
                <li><%= link_to "Chats", chat_rooms_path %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                <li><%= link_to current_user.username, current_user  %></li>
                <li class="nav-item btn-group" data-behavior="notifications">
                  <a class="dropdown-toggle nav-link" type="button" data-behavior="notifications-link" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= fa_icon "bell" %> <span data-behavior="unread-count"></span>
                  </a>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenu1" data-behavior="notification-items">
                    <!--
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                    -->
                  </div>
                </li>
              <% else %>
                <li><%= link_to "Sign In", new_user_session_path  %></li>
                <li><%= link_to "Sign Up", new_user_registration_path  %></li>
              <% end %>
            </ul>
          </div>
        </div>
        <% if mobile_device == "desktop"  %>
        <div class="col-md-6">
          <%= form_tag(users_path, method: 'get', class: 'navbar-form navbar-right') do %>
            <%= search_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search for a user...'  %>
            <%= submit_tag "Search", class: 'btn btn-default', :name => nil %>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
    <% end %>

    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_status.html.erb
<div class="contains-modal" id="myModal">

  <div class="modal-header">
    <button class="close" data-dismiss="modal">x</button>
    <h2>I want...</h2>
  </div>

  <div class="modal-body">
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
    <div class="field">
      <%= f.collection_radio_buttons :role, [[:seeker, 'Help!'], [:stepper, 'to help someone!']], :first, :last %>
    </div>

    <div class="field">
      <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
      <%= f.password_field :current_password, autocomplete: "off", class: 'form-control' %>
    </div></br>

    <div class="actions">
      <%= f.submit "Submit", class: 'btn btn-primary' %>
    </div>
    <% end %>
  </div>
</div>